name: coverage

on: [push, pull_request]

permissions: {}

jobs:
  coverage:
    if: github.repository == 'Swatinem/rust-cache'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Test `cargo-llvm-cov` on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - run: rustup toolchain install stable --profile minimal --component llvm-tools-preview --no-self-update

      - uses: taiki-e/install-action@d0f4f69b07c0804d1003ca9a5a5f853423872ed9 # v2.62.13
        with:
          tool: cargo-llvm-cov

      - uses: ./
        with:
          workspaces: tests

      - run: cargo llvm-cov --all-features --workspace
        working-directory: tests
